config/routes.rb
Rails.application.routes.draw do
  root to: 'search_analytics#index'

  resources :search_analytics
  post 'save_search', to: "search_analytics#save_search", as: "save_search"
  get 'show_search_analytics', to: "search_analytics#show_search_analytics", as: "show_search_analytics"
end

app/models/search_analytic.rb
class SearchAnalytic < ActiveRecord::Base
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/search_analytics_controller.rb
class SearchAnalyticsController < ApplicationController
  # GET /search_analytics
  # GET /search_analytics.json
  def index
    @search_analytic = SearchAnalytic.new
  end

  def show_search_analytics
    @search_analytics = SearchAnalytic.all.order(quantity: :desc)
  end

  def save_search
    @search_analytic = SearchAnalytic.find_or_initialize_by(article_title: search_analytic_params[:article_title])
    @search_analytic.quantity.nil? ? @search_analytic.quantity = 1 : @search_analytic.quantity += 1;

    respond_to do |format|
      if @search_analytic.save
        format.json { render json: I18n.t('search_analytics.index.results', article_title: @search_analytic.article_title).to_json, status: :ok }
      else
        format.json { render json: nil, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /search_analytics/1
  # DELETE /search_analytics/1.json
  def destroy
    SearchAnalytic.destroy_all
    respond_to do |format|
      format.html { redirect_to show_search_analytics_url, notice: 'Stats cleared.' }
      format.json { head :no_content }
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def search_analytic_params
      params.permit(:article_title)
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SearchAnalytics</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="wrapper">
    <div id="page-wrapper">
      <div class="wrapper wrapper-content">
        <div class="container">
          <%= yield %>
        </div>
      </div>
    </div>
  </div>
</body>
</html>

app/views/search_analytics/index.html.erb
<br/><br/>
<%= form_for(@search_analytic) do |f| %>
  <div class="row padding-top-20">
    <div class="col-xs-10">
      <div class="panel panel-default">
        <div class="panel-body">
          <div class="col-xs-10">
            <%= f.text_field :article_title, placeholder: t(".search"), class: "form-control", onkeyup: "save_search()" %>
          </div>
          <div class="col-xs-2">
            <%= link_to t(".show_analytics"), show_search_analytics_path, class: "btn btn-success" %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%= image_tag "ajax-loader.gif", class:"loading" %>
  <div id="results"></div>
<% end %>

app/views/search_analytics/show_search_analytics.html.erb
<br/><br/>
<%= link_to t(".back"), search_analytics_path, class: "btn btn-info" %>
<%= link_to t(".delete"), search_analytic_path(0), method: :delete,
            data: { confirm: t(".delete_confirm")}, class: "btn btn-danger"  %>
<br/><br/>
<div class="row">
  <div class="col-xs-12">
    <% if @search_analytics.empty? %>
      <%= t(".nothing_to_show") %>
    <% else %>
      <table class="table table-striped">
        <tr>
          <th><%= t(".article_title") %></th>
          <th><%= t(".frequency") %></th>
        </tr>
        <% @search_analytics.each do |search| %>
          <tr>
            <td><%= search.article_title %></td>
            <td><%= search.quantity %></td>
          </tr>
        <% end %>
      </table>
    <% end %>
  </div>
</div>